"""
Definition of all 163 company research parameters.
These parameters will be generated by Agent 1.
"""

from typing import List, Dict

# All 163 parameters as a list
COMPANY_PARAMETERS: List[str] = [
    # Company Basics (1-8)
    "name",
    "short_name",
    "logo_url",
    "category",
    "incorporation_year",
    "overview_text",
    "nature_of_company",
    "headquarters_address",
    
    # Geographic Presence (9-11)
    "operating_countries",
    "office_count",
    "office_locations",
    
    # People & Talent (12-15)
    "employee_size",
    "vision_statement",
    "mission_statement",
    "core_values",
    
    # Company Info (16-22)
    "history_timeline",
    "recent_news",
    "website_url",
    "linkedin_url",
    "twitter_handle",
    "facebook_url",
    "instagram_url",
    
    # Contact & Legal (23-31)
    "primary_contact_email",
    "primary_phone_number",
    "regulatory_status",
    "legal_issues",
    "esg_ratings",
    "supply_chain_dependencies",
    "geopolitical_risks",
    "macro_risks",
    "carbon_footprint",
    
    # Marketing & Brand (32-40)
    "ethical_sourcing",
    "marketing_video_url",
    "customer_testimonials",
    "website_quality",
    "website_rating",
    "website_traffic_rank",
    "social_media_followers",
    "glassdoor_rating",
    "indeed_rating",
    
    # Recognition & Positioning (41-48)
    "google_rating",
    "awards_recognitions",
    "brand_sentiment_score",
    "event_participation",
    "pain_points_addressed",
    "focus_sectors",
    "offerings_description",
    "top_customers",
    
    # Value Proposition & Competition (49-57)
    "core_value_proposition",
    "unique_differentiators",
    "competitive_advantages",
    "weaknesses_gaps",
    "key_challenges_needs",
    "key_competitors",
    "market_share_percentage",
    "sales_motion",
    "customer_concentration_risk",
    
    # Strategy & Roadmap (58-68)
    "exit_strategy_history",
    "benchmark_vs_peers",
    "future_projections",
    "strategic_priorities",
    "industry_associations",
    "case_studies",
    "go_to_market_strategy",
    "innovation_roadmap",
    "product_pipeline",
    "tam",
    "sam",
    
    # Market & Operations (69-76)
    "som",
    "leave_policy",
    "health_support",
    "fixed_vs_variable_pay",
    "bonus_predictability",
    "esops_incentives",
    "family_health_insurance",
    "relocation_support",
    
    # HR & Culture (77-89)
    "lifestyle_benefits",
    "hiring_velocity",
    "employee_turnover",
    "avg_retention_tenure",
    "diversity_metrics",
    "work_culture_summary",
    "manager_quality",
    "psychological_safety",
    "feedback_culture",
    "diversity_inclusion_score",
    "ethical_standards",
    "burnout_risk",
    "layoff_history",
    
    # Values & Mission (90-93)
    "mission_clarity",
    "sustainability_csr",
    "crisis_behavior",
    
    # Financial Metrics (94-107)
    "annual_revenue",
    "annual_profit",
    "revenue_mix",
    "valuation",
    "yoy_growth_rate",
    "profitability_status",
    "key_investors",
    "recent_funding_rounds",
    "total_capital_raised",
    "customer_acquisition_cost",
    "customer_lifetime_value",
    "cac_ltv_ratio",
    "churn_rate",
    "net_promoter_score",
    
    # Financial Health (108-111)
    "burn_rate",
    "runway_months",
    "burn_multiplier",
    
    # Work Environment (112-125)
    "remote_policy_details",
    "typical_hours",
    "overtime_expectations",
    "weekend_work",
    "flexibility_level",
    "location_centrality",
    "public_transport_access",
    "cab_policy",
    "airport_commute_time",
    "office_zone_type",
    "area_safety",
    "safety_policies",
    "infrastructure_safety",
    "emergency_preparedness",
    
    # Leadership (126-133)
    "ceo_name",
    "ceo_linkedin_url",
    "key_leaders",
    "warm_intro_pathways",
    "decision_maker_access",
    "contact_person_name",
    "contact_person_title",
    "contact_person_email",
    
    # Governance (134-143)
    "contact_person_phone",
    "board_members",
    "training_spend",
    "onboarding_quality",
    "learning_culture",
    "exposure_quality",
    "mentorship_availability",
    "internal_mobility",
    "promotion_clarity",
    "tools_access",
    
    # Role Quality (144-157)
    "role_clarity",
    "early_ownership",
    "work_impact",
    "execution_thinking_balance",
    "automation_level",
    "cross_functional_exposure",
    "company_maturity",
    "brand_value",
    "client_quality",
    "exit_opportunities",
    "skill_relevance",
    "external_recognition",
    "network_strength",
    "global_exposure",
    
    # Technology & Innovation (158-163)
    "technology_partners",
    "intellectual_property",
    "r_and_d_investment",
    "ai_ml_adoption_level",
    "tech_stack",
    "cybersecurity_posture",
    "partnership_ecosystem",
    "tech_adoption_rating"
]

# Parameter categories for organized processing
PARAMETER_CATEGORIES: Dict[str, List[str]] = {
    "company_basics": COMPANY_PARAMETERS[0:8],
    "geographic_presence": COMPANY_PARAMETERS[8:11],
    "people_talent": COMPANY_PARAMETERS[11:15],
    "company_info": COMPANY_PARAMETERS[15:22],
    "contact_legal": COMPANY_PARAMETERS[22:31],
    "marketing_brand": COMPANY_PARAMETERS[31:40],
    "recognition_positioning": COMPANY_PARAMETERS[40:48],
    "value_competition": COMPANY_PARAMETERS[48:57],
    "strategy_roadmap": COMPANY_PARAMETERS[57:68],
    "market_operations": COMPANY_PARAMETERS[68:76],
    "hr_culture": COMPANY_PARAMETERS[76:89],
    "values_mission": COMPANY_PARAMETERS[89:93],
    "financial_metrics": COMPANY_PARAMETERS[93:107],
    "financial_health": COMPANY_PARAMETERS[107:111],
    "work_environment": COMPANY_PARAMETERS[111:125],
    "leadership": COMPANY_PARAMETERS[125:133],
    "governance": COMPANY_PARAMETERS[133:143],
    "role_quality": COMPANY_PARAMETERS[143:157],
    "technology_innovation": COMPANY_PARAMETERS[157:163]
}

# Mandatory parameters (cannot be null)
MANDATORY_PARAMETERS: List[str] = [
    "name",
    "category",
    "incorporation_year",
    "overview_text",
    "nature_of_company",
    "headquarters_address",
    "employee_size",
    "focus_sectors",
    "offerings_description"
]


def get_parameter_category(parameter: str) -> str:
    """Get the category for a given parameter."""
    for category, params in PARAMETER_CATEGORIES.items():
        if parameter in params:
            return category
    return "unknown"


def validate_parameters():
    """Validate that all parameters are accounted for."""
    assert len(COMPANY_PARAMETERS) == 163, f"Expected 163 parameters, got {len(COMPANY_PARAMETERS)}"
    assert len(set(COMPANY_PARAMETERS)) == 163, "Duplicate parameters found"
    print(f"✅ All {len(COMPANY_PARAMETERS)} parameters validated")


if __name__ == "__main__":
    validate_parameters()
    print(f"\nParameter Categories:")
    for category, params in PARAMETER_CATEGORIES.items():
        print(f"  {category}: {len(params)} parameters")
